spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/central_register"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"

server:
  error:
    include-message: always
    include-binding-errors: always